DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.answers CASCADE;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.scores;